name: rename

on:
  push:
  # allow manually trigger
  workflow_dispatch:

jobs:
  rename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: download latest version of Sarasa Gothic from GitHub release page
        run: |
          # find the latest tag
          LATEST_TAG=$(curl --silent https://api.github.com/repos/jonz94/Sarasa-Gothic-Nerd-Fonts/releases/latest | jq -r .tag_name)
          echo downloading Sarasa Mono TC Nerd Fonts ${LATEST_TAG}
          curl -L https://github.com/jonz94/Sarasa-Gothic-Nerd-Fonts/releases/download/${LATEST_TAG}/sarasa-mono-tc-nerd-font.zip -O
      - run: ls -l
      - run: unzip *.zip
      - run: ls -l
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: rename
        run: |
          pip install fonttools
          python ${GITHUB_WORKSPACE}/main.py > output.txt
      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: output.txt
